name: Run Executable C++ Files

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile and Run Only Files With main()
      run: |
        for file in $(find . -name "*.cpp"); do
          if grep -q "int main" "$file"; then
            echo "Compiling $file"
            g++ "$file" -o output
            echo "Running $file"
            ./output
            echo "----------------------"
          else
            echo "Skipping $file (no main function)"
          fi
        done
