name: Compile C++ Files

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Compile Only C++ Files With main()
      run: |
        found=false
        for file in $(find . -name "*.cpp"); do
          if grep -q "int main" "$file"; then
            found=true
            echo "Compiling $file"
            g++ "$file" -o output
            echo "$file compiled successfully"
            echo "----------------------"
          else
            echo "Skipping $file (no main function)"
          fi
        done

        if [ "$found" = false ]; then
          echo "No executable C++ files found."
        fi
